"""empty message

Revision ID: 87d0dadf441c
Revises: acd9ab6e3f35
Create Date: 2024-06-02 16:25:01.744179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d0dadf441c'
down_revision = 'acd9ab6e3f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prichod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prichod')
    # ### end Alembic commands ###
